config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get     '/login',   to: 'sessions#new'
  post    '/login',   to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'

  resources :users
  get    '/signup',  to:'users#new'
  post   '/signup',  to: 'users#create'

  resources :jobs

  get 'weathers/index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/column.rb
class Column < ApplicationRecord
  belongs_to :job
  enum data_type: { 'Faker': 0, 'Other1': 1, 'Other2': 2 }
end

app/models/job.rb
class Job < ApplicationRecord
  has_many :columns, :dependent => :destroy
  accepts_nested_attributes_for :columns, :allow_destroy => true
  enum format: { CSV: 0, TSV: 1 }
  enum char_code: { 'utf-8': 0, 'Shift_JIS': 1 }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }, 
                    uniqueness: { case_sensitive: false }
  has_secure_password

  # nilを許可してもbcryptで「nilでない時だけdigestを更新」するから大丈夫
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private
      # ログイン済みユーザーかどうか確認
    def logged_in_user
      unless logged_in?
        flash[:danger] = "ログインしてください"
        redirect_to login_url
      end
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :logged_in_user

  def index
    @jobs = Job.all
  end

  def new
    @job = Job.new
    # 3.times {|i| @job.columns.push(Column.new(name:"name#{i}")) }
    3.times {|i| @job.columns.build(name:"name#{i}") }
  end

  def create
    @job = Job.new(job_params)
    if @job.save
      flash[:success] = "Jobを登録しました"
      redirect_to jobs_path
    else
      render 'new'
    end
  end

  def edit
    @job = Job.find(params[:id])
  end
  
  def update
    @job = Job.find(params[:id])
    if @job.update_attributes(job_params)
      flash[:success] = "ジョブを更新しました"
      redirect_to jobs_path
    else
      render 'edit'
    end
  end  

  def destroy
    Job.find(params[:id]).destroy
    flash[:success] = "ジョブを削除しました"
    redirect_to jobs_path
  end

  private

    def job_params
      #params.require(:job).permit(:name, :format, :char_code, columns_attributes:[:name, :data_type])
      #params.require(:job).permit(:name, :format, :char_code, :columns)
      #params.require(:job).permit(:name, :format, :char_code, :columns => [])
      #params.require(:job).permit(:name, :format, :char_code, {:columns => []})
      #params.require(:job).permit(:name, :format, :char_code, columns_attributes: [:id, :name, :data_type])
      params.require(:job).permit(:name, :format, :char_code, columns_attributes: [:id, :name, :data_type, :job_id])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      log_in @user
      redirect_to root_path
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "ユーザーを新規登録しました！"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました"
      redirect_to users_path
    else
      render 'edit'
    end
  end  

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "ユーザーを削除しました"
    redirect_to users_path
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
  
end

app/controllers/weathers_controller.rb
class WeathersController < ApplicationController
  def index
    agent = Mechanize.new
    agent.request_headers = {
      'Accept' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
      'Accept-Encoding' => 'gzip, deflate',
      'Accept-Language' => 'ja,en-US;q=0.8,en;q=0.6',
      'Cache-Control' => 'no-cache',
      'Connection' => 'keep-alive',
      'Content-Length' => '486',
      'Content-Type' => 'application/x-www-form-urlencoded',
      'Host' => 'www.data.jma.go.jp',
      'Origin' => 'http://www.data.jma.go.jp',
      'Pragma' => 'no-cache',
      'Referer' => 'http://www.data.jma.go.jp/gmd/risk/obsdl/index.php',
      'Upgrade-Insecure-Requests' => '1',
      'User-Agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36',
    }

    content_data = {
      stationNumList: ["s47662"],
      aggrgPeriod: 9,
      elementNumList: [["201", ""]],
      interAnnualFlag: 1,
      ymdList: ["2017", "2017", "8", "9", "24", "24"],
      optionNumList: [],
      downloadFlag: "true",
      rmkFlag: 1,
      disconnectFlag: 1,
      youbiFlag: 0,
      fukenFlag: 0,
      kijiFlag: 0,
      huukouFlag: 0,
      csvFlag: 1,
      jikantaiFlag: 0,
      jikantaiList: [1, 24],
      ymdLiteral: 0,
      PHPSESSID: get_phpsessid
    }
    page = agent.post('http://www.data.jma.go.jp/gmd/risk/obsdl/show/table', content_data)
    render html: page.body
  end

  private
  
    def get_phpsessid
      url = "http://www.data.jma.go.jp/gmd/risk/obsdl/index.php"
      agent = Mechanize.new
      page = agent.get(url)
      return page.search('input#sid')[0]['value']
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # ページごとの完全なタイトルを返します。
  def full_title(page_title = '')
    base_title = "Fake Data Maker"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end

  # 渡されたユーザーがログイン済みユーザーであればtrueを返す
  def current_user?(user)
    user == current_user
  end
  
  # 現在ログイン中のユーザーを返す (いる場合)
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end

  # 現在のユーザーをログアウトする
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weathers_helper.rb
module WeathersHelper
end

app/views/jobs/_column_fields.html.erb
<div>
    <%= f.text_field :id %>
    <%= f.text_field :job_id %>
    <%= f.label :name, "Amount" %>        
    <%= f.text_field :name %>
    <br>
    <%= f.label :data_type, "Renter" %>
    <%= f.select :data_type, Column.data_types.keys.to_a, {} %>
</div>

app/views/jobs/_form.html.erb
<h1><%= yield(:title) %></h1>

<div class="row">
  <%= form_for(@job, url: yield(:url), html: {class: 'form-horizontal'}) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <div class="form-group">
      <%= f.label :name, class: 'col-md-2 control-label' %>
      <div class="col-md-10">
        <%= f.text_field :name, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :format, class: 'col-md-2 control-label' %>
      <div class="col-md-10">
        <%= f.select :format, Job.formats.keys.to_a, {},class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :char_code, class: 'col-md-2 control-label' %>
      <div class="col-md-10">
        <%= f.select :char_code, Job.char_codes.keys.to_a, {},class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-10 col-md-offset-2">
        <%= f.submit yield(:button_text), class: "btn btn-primary" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.fields_for :columns do |builder| %>
        <%= render 'column_fields', :f => builder %>
      <% end %>
    </div>

  <% end %>
</div>

app/views/jobs/edit.html.erb
<% provide(:title, "ジョブの編集") %>
<% provide(:url, job_path(@job)) %>
<% provide(:button_text, '更新') %>
<%= render 'form' %>

app/views/jobs/index.html.erb
<h1>Jobs#index</h1>
<table class="table">
  <thead>
    <tr>
      <th>名称</th>
      <th>フォーマット</th>
      <th>文字コード</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @jobs.each do |job| %>
    <tr>
      <td><%= job.name %></td>
      <td><%= job.format %></td>
      <td><%= job.char_code %></td>
      <td>
        <%= link_to "編集", edit_job_path(job) %>
        <%= link_to "削除", job, method: :delete, data: { confirm: "本当に削除しますか？" } %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "新規登録", new_job_path %>

app/views/jobs/new.html.erb
<% provide(:title, "ジョブの新規登録") %>
<% provide(:url, jobs_path) %>
<% provide(:button_text, '新規登録') %>
<%= render 'form' %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default">
  <div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed"data-toggle="collapse"data-target="#navbarBody">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to "Home", root_path, class: "navbar-brand" %>
		</div>
		
		<div class="collapse navbar-collapse" id="navbarBody">
			<ul class="nav navbar-nav navbar-right">
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">メニュー <span class="caret"></span></a>
					<ul class="dropdown-menu" role="menu">
		        <% if logged_in? %>
      				<li><%= link_to "ユーザー一覧", users_path %></li>
      				<li><%= link_to "ジョブ一覧", jobs_path %></li>
              <li class="divider"></li>
      				<li><%= link_to "ログアウト", logout_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "ログイン", login_path %></li>
              <li class="divider"></li>
              <li><%= link_to "ユーザの新規登録", signup_path %></li>
            <% end %>
					</ul>
				</li>
			</ul>
			<p class="navbar-text navbar-right">ようこそ <%= current_user ? current_user.name : "ゲスト" %> さん。</p>
		</div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>This is home page.</h1>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<h1><%= yield(:title) %></h1>

<div class="row">
  <%= form_for(@user, url: yield(:url), html: {class: 'form-horizontal'}) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <div class="form-group">
      <%= f.label :name, class: 'col-md-2 control-label' %>
      <div class="col-md-10">
        <%= f.text_field :name, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :email, class: 'col-md-2 control-label' %>
      <div class="col-md-10">
        <%= f.email_field :email, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :password, class: 'col-md-2 control-label' %>
      <div class="col-md-10">
        <%= f.password_field :password, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation, "Confirmation", class: 'col-md-2 control-label' %>
      <div class="col-md-10">
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-10 col-md-offset-2">
        <%= f.submit yield(:button_text), class: "btn btn-primary" %>
      </div>
    </div>

  <% end %>
</div>

app/views/users/edit.html.erb
<% provide(:title, "ユーザの編集") %>
<% provide(:url, user_path(@user)) %>
<% provide(:button_text, '更新') %>
<%= render 'form' %>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>名前</th>
      <th>メールアドレス</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td>
        <%= link_to "編集", edit_user_path(user) %>
        <%= link_to "削除", user, method: :delete, data: { confirm: "本当に削除しますか？" } %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<% provide(:title, "ユーザの新規登録") %>
<% provide(:url, signup_path) %>
<% provide(:button_text, '新規登録') %>
<%= render 'form' %>

app/views/weathers/index.html.erb
<h1>Weathers#index</h1>

<% @elements.each do |element| %>
  <%= element.get_attribute(:id) %> <%= element.inner_text %><br>
<% end %>